version: "3.3"

services:

  # Backend API's
  user_authentication_and_authorization:
    container_name: user_auth_api
    build: ./user_authentication_and_authorization
    command: bundle install
    ports: 
      - "3001:3001"
    volumes: 
      - ./user_authentication_and_authorization:/home/jetter

  # Postgres database
  postgres:
    image: postgres:12
    ports:
      - "5433:5433"
    # volumes:
    #  - ./tmp/db:/var/lib/postgresql/data
