version: 2

jobs:
  build_user_authentication_and_authorization:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: localhost
          PGUSER: jetter
          RAILS_ENV: test
    steps:
      - checkout
      - run: echo "Pulling submodules"
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
            echo "Changing directory"
            cd user_authentication_and_authorization
            pwd
            echo "Running bundle install"
            bundle install
            echo "Setting up database"
            bundle exec rake db:create
            bundle exec rake db:migrate
            bundle exec rake db:seed
  build_jetter_client:
    docker:
      - image: circleci/node:8.16
    steps:
      - checkout
      - run: echo "Pulling submodules"
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
            echo "Changing directory"
            cd jetter-client
            pwd
            echo "Running npm install"
            npm install
            echo "Building project"
            npm run build
  test_user_authentication_and_authorization:
    docker:
      - image: circleci/ruby:2.6.3
        environment:
          PGHOST: localhost
          PGUSER: jetter
          RAILS_ENV: test
    steps:
      - checkout
      - run: echo "Pulling submodules"
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
            echo "Changing directory"
            cd user_authentication_and_authorization
            pwd
            echo "Running bundle install"
            bundle install
            echo "Setting up database"
            bundle exec rake db:create
            bundle exec rake db:migrate
            bundle exec rake db:seed
            echo "Running RSpec tests."
            rspec spec
  test_jetter_client:
    docker:
      - image: circleci/node:8.16
    steps:
      - checkout
      - run: echo "Pulling submodules"
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
            echo "Changing directory"
            cd jetter-client
            pwd
            echo "Running npm install"
            npm install
            echo "Running npm test"
            npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_user_authentication_and_authorization
      - build_jetter_client
      - test_user_authentication_and_authorization:
          requires:
            - build_user_authentication_and_authorization
      - test_jetter_client:
          requires:
            - build_jetter_client
