version: 2

jobs:
  build_user_authentication_and_authorization:
    docker:
      - image: cicrleci/ruby:2.6.3
    steps:
      - checkout
      - run: echo "Pulling submodules"
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: echo "Running bundle install"
      - run: bundle install
  build_jetter_client:
    docker:
      - image: cicrleci/node:8.16
    steps:
      - checkout
      - run: echo "Pulling submodules"
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: echo "Running npm install"
      - run: npm install
      - run: echo "Building project"
      - run: npm run build
  test_user_authentication_and_authorizationi:
    docker:
      - image: cicrleci/ruby:2.6.3
    steps:
      - checkout
      - run: echo "Pulling submodules"
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: "Running bundle install"
      - run: bundle install
      - run: echo "Running RSpec tests."
      - run: rspec spec
  test_jetter_client:
    docker:
      - image: cicrleci/node:8.16
    steps:
      - checkout
      - run: echo "Pulling submodules"
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: echo "Running npm install"
      - run: npm install
      - run: echo "Running npm test"
      - run: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_user_authentication_and_authorization
      - build_jetter_client
      - test_user_authentication_and_authorization:
          requires:
            - build_user_authentication_and_authorization
      - test_jetter_client:
          requires:
            - build_jetter_client
